name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore Jellyfin.Plugin.Facebook

      - name: Build
        run: dotnet build Jellyfin.Plugin.Facebook --configuration Release --no-restore

      - name: Test
        run: dotnet test Jellyfin.Plugin.Facebook --no-restore --verbosity normal
