name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from GITHUB_REF
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore Jellyfin.Plugin.Facebook

      - name: Build
        run: dotnet build Jellyfin.Plugin.Facebook --configuration Release --output dist --no-restore

      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'dist'
          filename: 'release.zip'
          exclusions: '*.json* *.pdb* /*ref/*'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/release.zip

      - name: MD5
        run: md5 dist/release.zip
